Experiment:
  id: 'exp-001'
  info: "Testing is going on"

Dataset:
  image:
    data_folder: 'G:\Image Captioning\Flicker8k_Dataset'
    extract_features: False
    feature_path: 'G:\Image Captioning\Pickle'

  text:
    data_folder: 'G:\Image Captioning\text_data\Flickr8k.token.txt'
    train_filepath: 'G:\Image Captioning\text_data\Flickr_8k.trainImages.txt'
    val_filepath: 'G:\Image Captioning\text_data\Flickr_8k.devImages.txt'
    test_filepath: 'G:\Image Captioning\text_data\Flickr_8k.testImages.txt'

    embedding_dir: 'G:\Image Captioning\GloVe\glove.6B.200d.txt'
    emb_save_dir: 'G:\Image Captioning\save_embedding_pickle'
    embedding_dim: 200

Trainer:
  optimizer: 'sgd'
  lr: 0.001
  lr_decay: False
  lr_decay_from: 10
  loss_fn: 'CategoricalCrossentropy'
  eval_metrics: ['accuracy']
  threshold: 0.7
  epochs: 1 # 3 to 20
  early_stop: False
  save_checkpoints: False
  save_model: True
  log_dir: 'G:\Image Captioning\tensorboard_logs'
  save_dir: 'G:\Image Captioning\trained_models'
  save_format: 'tf_pb'
